### PR TITLE
Add sessions call

### PR DESCRIPTION
**Pull request by gcatanese**

### CODE REVIEW

**Comment by jlengrand** [comment]
Closes #8

**Comment by jlengrand** [comment]
Fixes #8

**Comment by jlengrand** [comment]
Did you change any css? I'm having some responsive (or lack of) that is different from the other demos I've seen. For example with iDeal (if you test the flow with ideal you'll see the width of the dropdown change).

image

**Comment by jlengrand** [comment]
Nice! Not much to say about the code, it looks good! I do have some other comments, happy to chat tomorrow.

**Comment by gcatanese** [comment]
@jlengrand Removed the `platform` configuration to simplify the code and keep consistency. Please have another look.

I will create a new issue to implement HMAC validation in the Webhook

**Comment by jlengrand** [comment]
You have my blessing, do merge!

**Pull request merged**
